# Site settings

title: Abel's Blog

email: abel.liu.china@outlook.com

description: "Here is my blog include IT articles and essays."
baseurl: ""
url: "http://abelcloud.net"
username: "Abel-Liu"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
paginate: 10
paginate_path: "page:num"
excerpt_separator: <!--more-->
category_dir: _cat
tag_dir: _tag
future: true
gems:
  - jekyll-sitemap
  - jekyll-paginate