# Site settings

title: Abel's Blog

email: abel.liu.china@outlook.com

description: "Here is my blog include IT articles and essays."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
