# Site settings

title: Abel's Blog

email: abel.liu.china@outlook.com

description: "Here is my blog include IT articles and essays."
baseurl: ""
url: "http://www.abelliu.com"
username: "Abel-Liu"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 10
paginate_path: "page:num"
gems:
  - jekyll-sitemap